[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=77.0.3"]


[project]
name = "trusted_publishing"
description = "Simple python script to get a token from pypi"
requires-python = ">=3.12"
dependencies = [
    "id ~= 1.6.1",
    "requests ~= 2.34.0",
    # NOTE: Used to generate attestations.
    "pypi-attestations ~= 0.0.29",
    "sigstore ~= 4.1"
]
version = "0.1.0"

[project.scripts]
twine_id = "twine_id:main"
make_attestation = "attestation:main"