name: Create wheel

on:
  # TODO remove
  push:
    # branches:
    #   - master
    paths-ignore:
      - 'doc/**'
      - 'examples/**'
  release:
    types: [created]

env:
  PYTHONNOUSERSITE: 1

jobs:
  make-wheel:
    name: Create wheel on ${{ matrix.os }} python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - 'ubuntu-latest'
          - 'windows-latest'
          - 'macos-latest'
        python-version:
          # - '2.7'
          # - '3.5'
          # - '3.6'
          - '3.7'
          # - '3.8'
      fail-fast: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel

      - name: Create wheel
        run: |
          pip wheel -w dist --no-use-pep517 -v .

      - name: Install wheel
        run: |
          pip install -f dist --no-index sqlalchemy

      - name: Test created wheel
        run: |
          pip install pytest pytest-xdist
          pytest -n2 -q test -k 'not MockReconnectTest' --nomemory

      - name: Upload wheel
        uses: actions/upload-artifact@v1
        with:
          name: wheel-${{ matrix.os }}-${{ matrix.python-version }}
          path: dist
