name: Create wheel

on:
  release:
    types: [created]

env:
  PYTHONNOUSERSITE: 1

jobs:
  make-wheel:
    name: ${{ matrix.python-version }}-${{ matrix.architecture }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - 'ubuntu-latest'
          - 'windows-latest'
          # - 'macos-latest'
        python-version:
          - '2.7'
          # - '3.5'
          # - '3.6'
          # - '3.7'
          - '3.8'
        architecture:
          - x64
          - x86

        include:
          - python-version: '2.7'
            extra-requires: 'mock'

        exclude:
          - os: 'ubuntu-latest'
            architecture: x86
          - os: 'macos-latest'
            architecture: x86

      fail-fast: false

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}

      - name: Create wheel windows or osx
        if: matrix.os != 'ubuntu-latest'
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
          pip wheel -w dist --no-use-pep517 -v .

      - name: Create python PEP 425 tag for manylinux build
        id: linux-py-version
        if: matrix.os == 'ubuntu-latest'
        env:
          pyversion: ${{ matrix.python-version }}
        run: |
          pv="${pyversion/./}"
          echo $pv
          pytag="cp${pv}-cp${pv}m"
          echo "::set-output name=python-version::$pytag"

      - name: Create wheel for manylinux
        if: matrix.os == 'ubuntu-latest'
        uses: RalfG/python-wheels-manylinux-build@v0.2.2-manylinux2010_x86_64
        with:
          python-versions: ${{ steps.linux-py-version.outputs.python-version }}
          build-requirements: 'setuptools wheel'
          pip-wheel-args: '-w dist --no-use-pep517 -v --no-deps'

      # - name: Install wheel
      #   run: |
      #     pip install -f dist --no-index sqlalchemy

      # - name: Check c extensions
      #   # on windows in python 2.7 and 3.5 the cextension fail to build.
      #   # for python 2.7 visual studio 9 is missing
      #   # for python 3.5 the linker has an error "cannot run 'rc.exe'"
      #   if: matrix.os != 'windows-latest' || ( matrix.python-version != '2.7' && matrix.python-version != '3.5' )
      #   run: |
      #     python -c 'from sqlalchemy import cprocessors, cresultproxy, cutils'

      # - name: Test created wheel
      #   run: |
      #     pip install pytest pytest-xdist ${{ matrix.extra-requires }}
      #     pytest -n2 -q test -k 'not MockReconnectTest' --nomemory

      - name: Get wheel name
        id: wheel-name
        shell: bash
        # creates output from https://github.community/t5/GitHub-Actions/Using-the-output-of-run-inside-of-if-condition/td-p/33920
        run: |
          echo ::set-output name=wheel::`ls dist`

      - name: Upload wheel to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/${{ steps.wheel-name.outputs.wheel }}
          asset_name: ${{ steps.wheel-name.outputs.wheel }}
          asset_content_type: application/zip # application/octet-stream

      - name: Set up Python for twine
        # twine on py2 is very old.
        # the action 
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - name: Publish wheel
        env:
          TWINE_USERNAME: __token__
          # replace TWINE_PASSWORD with token for real pypi
          TWINE_PASSWORD: ${{ secrets.test_pypi_token }}
          # comment TWINE_REPOSITORY_URL to use the real pypi
          TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
        run: |
          pip install -U twine
          twine upload --skip-existing dist/*


  # download-artifact@v2 does not work. See https://github.com/actions/download-artifact/issues/23#issuecomment-605435160

  # create-artifact:
  #   name: Create a single artifact with all the wheels
  #   runs-on: 'ubuntu-latest'
  #   needs: make-wheel

  #   steps:
  #     - name: Download single wheels
  #       uses: actions/download-artifact@v2-preview
  #       with:
  #         path: single

  #     - name: Move in single folder
  #       shell: bash
  #       run: |
  #         mkdir wheels
  #         mv single/**/*.whl wheels

  #     - name: Upload wheel
  #       uses: actions/upload-artifact@v1
  #       with:
  #         name: all-wheels
  #         path: wheels

  # create-artifact:
  #   name: Create a single artifact with all the wheels
  #   runs-on: 'ubuntu-latest'
  #   needs: make-wheel

  #   steps:
  #     - name: Download single-wheel-ubuntu-latest-2.7-x64
  #       uses: actions/download-artifact@v1
  #       with:
  #         name: single-wheel-ubuntu-latest-2.7-x64
  #         path: wheels
  #     - name: Download single-wheel-ubuntu-latest-3.5-x64
  #       uses: actions/download-artifact@v1
  #       with:
  #         name: single-wheel-ubuntu-latest-3.5-x64
  #         path: wheels
  #     - name: Download single-wheel-ubuntu-latest-3.6-x64
  #       uses: actions/download-artifact@v1
  #       with:
  #         name: single-wheel-ubuntu-latest-3.6-x64
  #         path: wheels
  #     - name: Download single-wheel-ubuntu-latest-3.7-x64
  #       uses: actions/download-artifact@v1
  #       with:
  #         name: single-wheel-ubuntu-latest-3.7-x64
  #         path: wheels
  #     - name: Download single-wheel-ubuntu-latest-3.8-x64
  #       uses: actions/download-artifact@v1
  #       with:
  #         name: single-wheel-ubuntu-latest-3.8-x64
  #         path: wheels

  #     - name: Download single-wheel-windows-latest-2.7-x64
  #       uses: actions/download-artifact@v1
  #       with:
  #         name: single-wheel-windows-latest-2.7-x64
  #         path: wheels
  #     - name: Download single-wheel-windows-latest-3.5-x64
  #       uses: actions/download-artifact@v1
  #       with:
  #         name: single-wheel-windows-latest-3.5-x64
  #         path: wheels
  #     - name: Download single-wheel-windows-latest-3.6-x64
  #       uses: actions/download-artifact@v1
  #       with:
  #         name: single-wheel-windows-latest-3.6-x64
  #         path: wheels
  #     - name: Download single-wheel-windows-latest-3.7-x64
  #       uses: actions/download-artifact@v1
  #       with:
  #         name: single-wheel-windows-latest-3.7-x64
  #         path: wheels
  #     - name: Download single-wheel-windows-latest-3.8-x64
  #       uses: actions/download-artifact@v1
  #       with:
  #         name: single-wheel-windows-latest-3.8-x64
  #         path: wheels

  #     - name: Download single-wheel-windows-latest-2.7-x86
  #       uses: actions/download-artifact@v1
  #       with:
  #         name: single-wheel-windows-latest-2.7-x86
  #         path: wheels
  #     - name: Download single-wheel-windows-latest-3.5-x86
  #       uses: actions/download-artifact@v1
  #       with:
  #         name: single-wheel-windows-latest-3.5-x86
  #         path: wheels
  #     - name: Download single-wheel-windows-latest-3.6-x86
  #       uses: actions/download-artifact@v1
  #       with:
  #         name: single-wheel-windows-latest-3.6-x86
  #         path: wheels
  #     - name: Download single-wheel-windows-latest-3.7-x86
  #       uses: actions/download-artifact@v1
  #       with:
  #         name: single-wheel-windows-latest-3.7-x86
  #         path: wheels
  #     - name: Download single-wheel-windows-latest-3.8-x86
  #       uses: actions/download-artifact@v1
  #       with:
  #         name: single-wheel-windows-latest-3.8-x86
  #         path: wheels

  #     - name: Download single-wheel-macos-latest-2.7-x64
  #       uses: actions/download-artifact@v1
  #       with:
  #         name: single-wheel-macos-latest-2.7-x64
  #         path: wheels
  #     - name: Download single-wheel-macos-latest-3.5-x64
  #       uses: actions/download-artifact@v1
  #       with:
  #         name: single-wheel-macos-latest-3.5-x64
  #         path: wheels
  #     - name: Download single-wheel-macos-latest-3.6-x64
  #       uses: actions/download-artifact@v1
  #       with:
  #         name: single-wheel-macos-latest-3.6-x64
  #         path: wheels
  #     - name: Download single-wheel-macos-latest-3.7-x64
  #       uses: actions/download-artifact@v1
  #       with:
  #         name: single-wheel-macos-latest-3.7-x64
  #         path: wheels
  #     - name: Download single-wheel-macos-latest-3.8-x64
  #       uses: actions/download-artifact@v1
  #       with:
  #         name: single-wheel-macos-latest-3.8-x64
  #         path: wheels


  #     - name: Upload wheel
  #       uses: actions/upload-artifact@v1
  #       with:
  #         name: all-wheels
  #         path: wheels

